/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetManager: typeof import('./src/components/AssetManager.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ConversionSettings: typeof import('./src/components/settings/ConversionSettings.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    NSpin: typeof import('naive-ui')['NSpin']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTag: typeof import('naive-ui')['NTag']
    ProfileForm: typeof import('./src/components/settings/ProfileForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscriptionNodesPreview: typeof import('./src/components/SubscriptionNodesPreview.vue')['default']
  }
}
